# Khởi chạy server Backend ở cổng 8080
server.port=8080

# ==========================================
# KẾT NỐI VỚI CƠ SỞ DỮ LIỆU ĐÁM MÂY AIVEN
# ==========================================
spring.datasource.url=jdbc:mysql://parknow-cloud-ldoan263204-c1be.f.aivencloud.com:23446/defaultdb?useSSL=true&requireSSL=true
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_1Frl0Fq11EgSIcZB9Bh
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# CẤU HÌNH JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# CẤU HÌNH JWT
# ==========================================
# Secret key 256-bit (Base64). Thay bằng chuỗi random của bạn khi deploy.
jwt.secret=cGFya25vdy1zZWNyZXQta2V5LWZvci1qd3QtdG9rZW4tMjAyNg==
# Thời hạn token: 86400000ms = 24 giờ
jwt.expiration=86400000
logging.level.org.springframework.security=DEBUG

# ==========================================
# STATIC RESOURCES — Serve ảnh upload
# ==========================================
spring.web.resources.static-locations=classpath:/static/,file:uploads/
spring.web.resources.add-mappings=true

# ==========================================
# MULTIPART FILE UPLOAD
# ==========================================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
